### ISSUE TITLE
error: No compatible build found (for 0.0.28 version)

### ISSUE THREAD

**Issue by henriquesobral** [CollectionFS/DEPRECATING-cfs-gridfs#16]
Hi,

I'm getting this error when I try to add cfs:gridfs to my meteor project.
```
While checking for cfs:gridfs@0.0.28:
error: No compatible build found
```

I'm using a Mac.
```
Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64
```

My meteor version
```

Meteor 1.0.3.2
```

Thanks

**Comment by antalakas** [comment]
Same problem here..

**Comment by raix** [comment]
Thanks - We are tracking it on the main repo + meteor repo (it's an issue related to publishing binary packages to windows)
